# deploy/docker-compose.yml

# Feel free to use this:
# https://dev.to/frankalvarez/dockerize-a-laravel-11-app-4g4a

version: '3.9'

services:
  laravel:
    restart: unless-stopped
    container_name: laravelapp
    build:
      context: ../
      dockerfile: ./deploy/Dockerfile
    volumes:
      - configurator_app:/var/www/fantom/storage/app
#      - fantom-configurator-cc_configurator_cc:/content
    environment:
      DB_HOST: database
    ports:
        - "8000:80"
    env_file:
        -   .env
    networks:
        -   n-laravel
    depends_on:
      database:
        condition: service_healthy

  database:
      restart: unless-stopped
      image: mariadb:10.6
      env_file:
          -  .env
      environment:
        MYSQL_DATABASE: "${DB_DATABASE}"
        MYSQL_USER: "${DB_USERNAME}"
        MYSQL_PASSWORD: "${DB_PASSWORD}"
        MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      volumes:
          - configurator_database:/var/lib/mysql
      healthcheck:
        test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '--password=password']
#        test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
        timeout: 20s
        retries: 1
      networks:
        -   n-laravel
      ports:
        - 3306:3306
      extra_hosts:
        - "host.docker.internal:host-gateway"
volumes:
  configurator_app: {}
  configurator_database: {}
#  fantom-configurator-cc_configurator_cc:
#    external: true

networks:
  n-laravel:
    driver: bridge
