# deploy/docker-compose.yml

# Feel free to use this:
# https://dev.to/frankalvarez/dockerize-a-laravel-11-app-4g4a

version: '3.9'

services:
  laravel:
    restart: unless-stopped
    container_name: laravelapp
    build:
      context: ../
      dockerfile: ./deploy/Dockerfile    
    volumes:
      - ../storage/app:/var/www/html/storage/app
      - fantom-configurator-cc_configurator_cc:/content
    environment:
      APP_NAME: ${APP_NAME}
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
      APP_KEY: ${APP_KEY}
      APP_VERSION: ${APP_VERSION}
      APP_URL: ${APP_URL}
      DB_CONNECTION: mysql
      DB_HOST: database
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      MAIL_MAILER: ${MAIL_MAILER}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_ENCRYPTION: ${MAIL_ENCRYPTION}
      MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS}
      MAIL_FROM_NAME: ${MAIL_FROM_NAME}
    ports:
      - "8000:8000"
    networks:
      - n-laravel
    depends_on:
      database:
        condition: service_healthy

  database:
    restart: unless-stopped
    image: mariadb:lts-jammy
    environment:
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - configurator_database:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '--password=password', '-u', 'root']
      timeout: 20s
      retries: 10
    networks:
      - n-laravel
    ports:
      - 3306:3306
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  configurator_app: {}
  configurator_database: {}
  fantom-configurator-cc_configurator_cc:
    external: true

networks:
  n-laravel:
    driver: bridge
